ALTER TABLE "SiteAccess" ADD COLUMN "accuracy" DOUBLE PRECISION;
ALTER TABLE "SiteAccess" ADD COLUMN "address" TEXT NOT NULL DEFAULT '';
ALTER TABLE "SiteAccess" ADD COLUMN "locationSource" TEXT NOT NULL DEFAULT 'ip';
